### ISSUE TITLE
Provide .ioc file.

### ISSUE THREAD

**Issue by InterestingWalrus** [MaJerle/stm32h7-dual-core-inter-cpu-async-communication#1]
Hi, not so much an issue but a request/suggestion. Would it be possible for you to provide the ioc file that comes with the STM32CudeIDE toolcahin with the project?

**Comment by MaJerle** [comment]
I can provide, but please keep in mind that it was generated only UART config for debug. The rest has not been used as it is not necessary for this particular example.

**Comment by InterestingWalrus** [comment]
That ctually makes sense. Thanks.
