### ISSUE TITLE
BOOT Options for CM4 Core is missing

### ISSUE THREAD

**Issue by 4ptrextor** [MaJerle/stm32h7-dual-core-inter-cpu-async-communication#3]
Hi, I'm trying to run this example on my Nucleo H745ZI-Q but I'm trying to set the option bytes in STM32Cube Programmer. However, I can't seem to find options for this as shown in your repositiory. Mine looks like this:

![image](https://user-images.githubusercontent.com/64443819/87494330-99e2a800-c646-11ea-8e2a-b513f14eeb25.png)

and the BCM4 option is also missing from my User config section. Do you have any ideas why this could be the case?

![image](https://user-images.githubusercontent.com/64443819/87494354-aff06880-c646-11ea-9fb3-bbf4df5b4f08.png)

**Comment by MaJerle** [comment]
Are you sure you have H745 device and not H743 instead?
Did you update STM32CubeProgrammer to latest version? At least 2.3 or newer?

**Comment by 4ptrextor** [comment]
Yes I'm running the nucleo-H745ZI-Q Nucleo Board.  This even shows on the device information tab on Cube Programmer. 
![image](https://user-images.githubusercontent.com/64443819/87534830-74798c80-c68e-11ea-9c84-96ee67e29f2a.png)

**Comment by 4ptrextor** [comment]
Finally managed to get it working by upgrading the firmware. STM32 CubeProgrammer wcouldn't find latest firware but CubeIDE managed to update STLink for me.
