### ISSUE TITLE
Question: Race-Condition Safe?

### ISSUE THREAD

**Issue by ZiGaMi** [MaJerle/stm32h7-dual-core-inter-cpu-async-communication#6]
I'm looking at your ring_buffer implementation and I don't see any sort of multiple access prevention mechanism to save you from race-conditions.

What am I looking into is "ring_buffer_write" and "ring_buffer_read". I know that you are using producer/consumer relationship. So for example lets say that CoreM7 is producer and CoreM4 is consumer. Therefore CoreM7 is only calling "ring_buffer_write" and respectfully CoreM4 is calling only "ring_buffer_read" functions.

Between those two function there is a direct linkage, as they are using the same ring buffer instance. Example given **buff->r** member.

From ringbuff.c line 186 inside "ringbuff_read()" you change **r** member:
```C
buff->r += tocopy;
```

And same member is being evaluated inside "ringbuff_get_free()" and that func is called from "ringbuff_write()" function line 131, 132:
```C
  /* Calculate maximum number of bytes available to write */
  free = ringbuff_get_free(buff);
```

So what happens when CoreM4 (as consumer) reads buffer right after CoreM7 (provider) execute "ringbuff_get_free()" function inside write function. Meaning that write function is not completed yet but right after evaluation of **buff->r** there is some code left to be executed. Perhaps this can change write function flow in un-expected manner.

Does it possible have some sort of hidden side-effects?

**Comment by MaJerle** [comment]
Getfree/getfull function first copies the r and w values and operates on these 2.

- Write function will check for free space (how much is available inside)
- Read function will check for full space (how much is inside)

Because it works on copied variables, it can not be affected by another CPU variable modification.

Only problem that may be is if optimizer ignores local variables for getfree and getfull functions and uses global ones from ring buffer directly.

I do not see other problem - but I may be wrong.

**Comment by ZiGaMi** [comment]
OK, I see that now and it makes sense.

Other think I noticed right now is that you are making memcpy first and then manipulate the read/write (Tail/Head) pointers. 

Inside "ringbuff_write" lines 139-142:
```C
    tocopy = BUF_MIN(buff->size - buff->w, btw);
    BUF_MEMCPY(&buff->buff[buff->w], d, tocopy);
    buff->w += tocopy;
```

And similar to read function:
```C
    BUF_MEMCPY(d, &buff->buff[buff->r], tocopy);
    buff->r += tocopy;
```


That mechanism protects you from race-conditions as well. Would you agree?

**Comment by MaJerle** [comment]
Yes - you need to load data first, only then you can modify variable. If it is opposite, another cpu can read non-loaded data.

And write funcrion only modifies w pointer, read only r pointer. Everything else uses read only - local vars.
